apiVersion: v1
kind: Pod
metadata:
  name: logging-sidercar
  labels:
    name: logging-sidecar-example 
    exmaple: logging-sidercar
spec:
  containers: 
  - name: systheic-logger
    image: ubuntu:14.04
    command: ["bash","-c","i=0; while true; do echo \" `hostname`:$i \" >> /var/log/synthetic-count.log; date --rfc-3339 ns >> /var/log/synthetic-dates.log; sleep 1; i=$[$i+1]; done"]
    volumeMounts: 
    - name: log-storage
      mountPath: /var/log
  - name: sidecar-log-collector
    image: gcr.io/google_containers/fluentd-sidecar-es:1.2
    resource:
      limits:
        cpu: 100m
        memory: 200Mi
    env:
    - name: FILES_TO_COLLECT
      value: "/var/log/synthetic-count.log /var/log/synthetic-dates.log"
    volumeMounts:
    - name: log-storage
      mountPath: /var/log
    command: ["/bin/sh","-c","/usr/local/sbin/config_generator.sh && /usr/sbin/td-agent --use-v1-config --suppress-repeated-stacktrace > /var/log/td-agent.log"]
  volumes:
  - name: log-storage
    emptyDir: {} 
